### ISSUE TITLE
Passing empty string to ISO8601.fromString should return an error

### ISSUE THREAD

**Issue by girishso** [jweir/elm-iso8601#11]
Currently, if we pass an empty string to `ISO8601.fromString` it returns invalid time

```
> ISO8601.fromString ""
Ok { day = 1, hour = 0, millisecond = 0, minute = 0, month = 1, offset = (0,0), second = 0, year = 0 }
    : Result String ISO8601.Time
```

It should return an error.

**Comment by jweir** [comment]
This is patched for Elm 0.19 

And if you need Elm 0.18 support try to install:
https://package.elm-lang.org/packages/jweir/elm-iso8601/4.0.4

**Comment by jweir** [comment]
And thanks for the bug report!  Close this out of if it looks good to you.

**Comment by girishso** [comment]
Thanks @jweir ! We're using 0.19.
