### ISSUE TITLE
confusion around offset

### ISSUE THREAD

**Issue by mordrax** [jweir/elm-iso8601#14]
```
> import ISO8601
> snooze = { day = 6, hour = 12, millisecond = 0, minute = 35, month = 11, offset = (0,0), second = 0, year = 2018 }

> now = { day = 6, hour = 1, millisecond = 0, minute = 40, month = 11, offset = (11,0), second = 0, year = 2018 }

> ISO8601.diff snooze now
78900000 : Int
> ISO8601.toTime snooze  
1541507700000 : Int
> ISO8601.toTime now   
1541428800000 : Int
> compare (ISO8601.toTime snooze) (ISO8601.toTime now)
GT : Order
```

`Snooze` is at 12hr 35mins of the day and `now` is at 1hr 40mins, however `now` has an offset of +11hrs so it's actually 12hr 40mins.

It seems that toTime and diff is not taking the offset into account when calculating time.

This is a problem when asking elm/time for the time now which when converted gives the _local_ time with an offset but then when compared with a UTC time, doesn't take the offset into account.

**Comment by mordrax** [comment]
Put another way: I thought these should be the same :
```
now = { day = 6, hour = 1, millisecond = 0, minute = 40, month = 11, offset = (11,0), second = 0, year = 2018 }

-- and

nowUTC = { day = 6, hour = 12, millisecond = 0, minute = 40, month = 11, offset = (0,0), second = 0, year = 2018 }

-- note the offset and hr differences
```

**Comment by jweir** [comment]
The offset is incorrect, the `now` is 11 hours ahead of the `nowUTC`.  The offset is stored (hours,minutes) from GMT.  

If you change `now` to  (note the negative hour)

```elm
 now = { day = 6, hour = 1, millisecond = 0, minute = 40, month = 11, offset = (-11,0), second = 0, year = 2018 }
```

You will get
```
> ISO8601.diff now nowUTC
0 
```

Does this make sense?

**Comment by mordrax** [comment]
Re-looking at my Posix to Time conversion, it now makes sense, thanks!

```
SessionTick client time: : Posix 1541726221581
elm.js:1174 SessionTick client time as ISO: { day = 9, hour = 1, millisecond = 581, minute = 17, month = 11, offset = (11,0), second = 2, year = 2018 }
```
